// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package jp.com.inotaku.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import jp.com.inotaku.domain.CustomerAttributeDataOnDemand;
import jp.com.inotaku.domain.CustomerAttributeIntegrationTest;
import jp.com.inotaku.repository.CustomerAttributeRepository;
import jp.com.inotaku.service.CustomerAttributeService;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CustomerAttributeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CustomerAttributeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CustomerAttributeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CustomerAttributeIntegrationTest: @Transactional;
    
    @Autowired
    CustomerAttributeDataOnDemand CustomerAttributeIntegrationTest.dod;
    
    @Autowired
    CustomerAttributeService CustomerAttributeIntegrationTest.customerAttributeService;
    
    @Autowired
    CustomerAttributeRepository CustomerAttributeIntegrationTest.customerAttributeRepository;
    
    @Test
    public void CustomerAttributeIntegrationTest.testCountAllCustomerAttributes() {
        Assert.assertNotNull("Data on demand for 'CustomerAttribute' failed to initialize correctly", dod.getRandomCustomerAttribute());
        long count = customerAttributeService.countAllCustomerAttributes();
        Assert.assertTrue("Counter for 'CustomerAttribute' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CustomerAttributeIntegrationTest.testFindCustomerAttribute() {
        CustomerAttribute obj = dod.getRandomCustomerAttribute();
        Assert.assertNotNull("Data on demand for 'CustomerAttribute' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CustomerAttribute' failed to provide an identifier", id);
        obj = customerAttributeService.findCustomerAttribute(id);
        Assert.assertNotNull("Find method for 'CustomerAttribute' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'CustomerAttribute' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CustomerAttributeIntegrationTest.testFindAllCustomerAttributes() {
        Assert.assertNotNull("Data on demand for 'CustomerAttribute' failed to initialize correctly", dod.getRandomCustomerAttribute());
        long count = customerAttributeService.countAllCustomerAttributes();
        Assert.assertTrue("Too expensive to perform a find all test for 'CustomerAttribute', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<CustomerAttribute> result = customerAttributeService.findAllCustomerAttributes();
        Assert.assertNotNull("Find all method for 'CustomerAttribute' illegally returned null", result);
        Assert.assertTrue("Find all method for 'CustomerAttribute' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CustomerAttributeIntegrationTest.testFindCustomerAttributeEntries() {
        Assert.assertNotNull("Data on demand for 'CustomerAttribute' failed to initialize correctly", dod.getRandomCustomerAttribute());
        long count = customerAttributeService.countAllCustomerAttributes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<CustomerAttribute> result = customerAttributeService.findCustomerAttributeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'CustomerAttribute' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'CustomerAttribute' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CustomerAttributeIntegrationTest.testFlush() {
        CustomerAttribute obj = dod.getRandomCustomerAttribute();
        Assert.assertNotNull("Data on demand for 'CustomerAttribute' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CustomerAttribute' failed to provide an identifier", id);
        obj = customerAttributeService.findCustomerAttribute(id);
        Assert.assertNotNull("Find method for 'CustomerAttribute' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCustomerAttribute(obj);
        Integer currentVersion = obj.getVersion();
        customerAttributeRepository.flush();
        Assert.assertTrue("Version for 'CustomerAttribute' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CustomerAttributeIntegrationTest.testUpdateCustomerAttributeUpdate() {
        CustomerAttribute obj = dod.getRandomCustomerAttribute();
        Assert.assertNotNull("Data on demand for 'CustomerAttribute' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CustomerAttribute' failed to provide an identifier", id);
        obj = customerAttributeService.findCustomerAttribute(id);
        boolean modified =  dod.modifyCustomerAttribute(obj);
        Integer currentVersion = obj.getVersion();
        CustomerAttribute merged = customerAttributeService.updateCustomerAttribute(obj);
        customerAttributeRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'CustomerAttribute' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CustomerAttributeIntegrationTest.testSaveCustomerAttribute() {
        Assert.assertNotNull("Data on demand for 'CustomerAttribute' failed to initialize correctly", dod.getRandomCustomerAttribute());
        CustomerAttribute obj = dod.getNewTransientCustomerAttribute(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'CustomerAttribute' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'CustomerAttribute' identifier to be null", obj.getId());
        try {
            customerAttributeService.saveCustomerAttribute(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        customerAttributeRepository.flush();
        Assert.assertNotNull("Expected 'CustomerAttribute' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CustomerAttributeIntegrationTest.testDeleteCustomerAttribute() {
        CustomerAttribute obj = dod.getRandomCustomerAttribute();
        Assert.assertNotNull("Data on demand for 'CustomerAttribute' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CustomerAttribute' failed to provide an identifier", id);
        obj = customerAttributeService.findCustomerAttribute(id);
        customerAttributeService.deleteCustomerAttribute(obj);
        customerAttributeRepository.flush();
        Assert.assertNull("Failed to remove 'CustomerAttribute' with identifier '" + id + "'", customerAttributeService.findCustomerAttribute(id));
    }
    
}
