// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package jp.com.inotaku.domain;

import jp.com.inotaku.domain.CustomerAttribute;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CustomerAttribute_Roo_Configurable {
    
    declare @type: CustomerAttribute: @Configurable;
    
}
